steps:
  # Step 1: Build Docker image for the backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/exam-portal-ns/exam-portal-api:$SHORT_SHA'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/exam-portal-ns/exam-portal-api:latest'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend' # Use the backend directory as build context

  # Step 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/exam-portal-ns/exam-portal-api:$SHORT_SHA'

  # Step 3: Deploy using gcloud
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'exam-portal-api'
      - '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/exam-portal-ns/exam-portal-api:$SHORT_SHA'
      - '--platform=managed'
      - '--region=$_REGION'
      - '--allow-unauthenticated'
      - '--set-env-vars=PORT=8080,TURSO_DATABASE_URL=$$TURSO_DATABASE_URL,TURSO_AUTH_TOKEN=$$TURSO_AUTH_TOKEN'
    secretEnv:
      - 'TURSO_DATABASE_URL'
      - 'TURSO_AUTH_TOKEN'

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/exam-portal-ns/exam-portal-api:$SHORT_SHA'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/exam-portal-ns/exam-portal-api:latest'

substitutions:
  _REGION: 'asia-south1'

options:
  machineType: 'E2_STANDARD_2'
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/turso-database-url/versions/latest
      env: 'TURSO_DATABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/turso-auth-token/versions/latest
      env: 'TURSO_AUTH_TOKEN'

timeout: 3600s