steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ns-exam-portal-backend', '.']

  # 2. Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ns-exam-portal-backend']

  # 3. Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ns-exam-portal-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ns-exam-portal-backend'
      - '--region'
      - 'asia-south1' # You can change this to your preferred GCP region
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/ns-exam-portal-backend'
